databases:
  - name: motorcycle-appointment
    databaseName: motorcycle_appointment
    user: 
motorcycle_appointment_user

services:
  - type: web
    name: motorcycle-appointment
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: motorcycle-appointment
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
