databases:
  - name: Budget-app
    databaseName: budget_app_mvb4
    user: 
budget_app_mvb4_user

services:
  - type: web
    name: Budget-app
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
